# based on example XXX
#  requires:

ARDMK_DIR       = /opt/Arduino-Makefile
ARDUINO_SKETCHBOOK = /home/taps/arduino
#USER_LIB_PATH  =
ARDUINO_LIBS    = CmdMessenger OneWire

BOARD_TAG = pro328
MONITOR_PORT      = /dev/ttyAMA0
MONITOR_BAUDRATE  = 57600

### path to Arduino.mk, inside the ARDMK_DIR, don't touch.
include $(ARDMK_DIR)/Arduino.mk
